### ISSUE TITLE
Swift 3 branch shows errors

### ISSUE THREAD

**Issue by kunalgupta1593** [jobandtalent/AnimatedTextInput#26]
Swift 3 branch is full of error . Please fix them

**Comment by bytemines** [comment]
Hello @kunalgupta1593, is full of errors due to the migration is not yet done.

Alternative to solve it you can use my branch, you can easily add it to your Podfile:

pod 'AnimatedTextInput', git: "https://github.com/ConradoMateu/AnimatedTextInput", branch: "swift3-integration"

(has one error but until the migration is completely done is one solution :) )

**Comment by nitrag** [comment]
@ConradoMateu your branch works, thanks!

Can you take a look at: https://github.com/jobandtalent/AnimatedTextInput/issues/27 ?

**Comment by victorBaro** [comment]
Hi guys, the pod has officially been updated to swift 3. 

Check version 0.4.0

https://github.com/jobandtalent/AnimatedTextInput/releases/tag/0.4.0

**Comment by kunalgupta1593** [comment]
Oh very Nice..!! Thanks for the effort bro ;-)
