### ISSUE TITLE
Keyboard Type

### ISSUE THREAD

**Issue by cesarmtz93** [jobandtalent/AnimatedTextInput#33]
Is there a way i can do something like this

`textInputs[3].keyboardType = .phonePad`

currently is not letting me

**Comment by victorBaro** [comment]
Hello @cesarmtz93 
You should set the keyboard type through `AnimatedTextInputFieldConfigurator`.
There are already many configurators. For example, `AnimatedTextInputEmailConfigurator` sets the keyboard type as `emailAddress`. 
You can use any of the available types (standard, email, password, numeric, selection, multiline).

You can also create and set your own configurator. For example:

```swift 
// Create your animatedTextInput
let textInput = AnimatedTextInput()
//create your custom type
let customTextInput = createCustomInput()
//Give it custom type
textInput.type = .custom(textInput: customTextInput)


func createCustomInput() -> TextInput {
// You can use any of the existing types, either animatedTextField or animatedTextView, or create your own textfield/textview subclasses
    let textField = AnimatedTextField()
    textField.clearButtonMode = .whileEditing
    textField.autocorrectionType = .no
    textField.clearButtonMode = .whileEditing
    textField.keyboardType = .phonePad
    return textField
}
```

I hope that makes sense!

--------

Since you raised that question, it makes me think if we should add a few options to the existing types to make the configuration a bit easier. 
Thank you for using this control!

**Comment by cesarmtz93** [comment]
@victorBaro Thank you so much!! and yeah you guys should do that configuration! it would help a lot! 

btw awesome control! i'm loving it!

**Comment by cesarmtz93** [comment]
@victorBaro if i would want to add a tool bar to a numeric keyboard it trowing me an error 

`textInputs[0].type = .numeric`
`textInputs[0].inputAccessoryView = toolBar`

it´s a get property any ideas on how to implement it?
